spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${CONSOLE_DB_URL:jdbc:mysql://mysql:3306/e_hub?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${CONSOLE_DB_USERNAME:root}
    password: ${CONSOLE_DB_PASSWORD:}

  # redis
  redis:
    host: ${CONSOLE_REDIS_HOST:redis}
    port: ${CONSOLE_REDIS_PORT:6379}
    database: ${CONSOLE_REDIS_DATABASE:0}
    password: ${CONSOLE_REDIS_PASSWORD:}
    timeout: 6000
    jedis:
      pool:
        max-active: 300
        min-idle: 10
        max-idle: 100
        max-wait: 4000


#大数据
bigdata:
  userKey: ${BIGDATA_USER_KEY:}
  data-collector: ${BIGDATA_DATA_COLLECTOR:http://localhost:8080}

#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'

#appId
app:
  id: e-hub-console-dev

swagger:
  enable: true

# apollo配置
apollo:
  check: default

# 服务器配置
server:
  keystore-alias: default-alias
