spring:
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.39.48.241:3306/load-aggregator?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #    username: fn_db_test
    #    password: fn_db_test20180411
    username: rootroot
    password: Abcd1234

  # redis
  redis:
    sentinel:
      master: master6379
      nodes: 10.39.47.6:26379,10.39.47.7:26379,10.39.47.8:26379
    #    host: 10.39.47.244
    #    port: 6379
    database: 15
    password: FNpreadmin123
    timeout: 6000
    jedis:
      pool:
        max-active: 300
        min-idle: 10
        max-idle: 100
        max-wait: 4000

bigdata:
  simulate: http://bigdata-api-simulate.pre.fnwintranet.com
  userKey: 03f9da7a41382f7199b9ad190872096c_e-hub-upstream
  data-collector: http://data-collector.fnwintranet.com

iot:
  baseUrl: http://iot-api-gateway-app.uat.fnwintranet.com/
  url: http://iot-api-gateway-app.uat.fnwintranet.com/api/v1/iot-service-open/down/cmd/set
  token: mH6KOV1QVLGdEUiX
  XAUTHID: unattendedServicec
  callBackUrl: http://e-hub-upstream.uat.fnwintranet.com/iot/callBack

# elk
app:
  id: e-hub-upstream
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        uri: http://10.39.61.11:8086
        enabled: true
        db: applications
    web:
      server:
        request:
          autotime:
            enabled: true

devops:
  logging:
    topic: fnw_logging_kafka_topic_pre

# swagger
swagger:
  enable: true