spring:
  # mysql
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${UPSTREAM_DB_URL}
    username: ${UPSTREAM_DB_USERNAME}
    password: ${UPSTREAM_DB_PASSWORD}

  # redis
  redis:
    sentinel:
      master: ${UPSTREAM_REDIS_SENTINEL_MASTER}
      nodes: ${UPSTREAM_REDIS_SENTINEL_NODES}
    database: ${UPSTREAM_REDIS_DATABASE:0}
    password: ${UPSTREAM_REDIS_PASSWORD:}
    timeout: 6000
    jedis:
      pool:
        max-active: 300
        min-idle: 10
        max-idle: 100
        max-wait: 4000

bigdata:
  userKey: ${BIGDATA_USER_KEY:}
  data-collector: ${BIGDATA_DATA_COLLECTOR}

iot:
  baseUrl: ${IOT_BASE_URL}
  url: ${IOT_COMMAND_URL}
  token: ${IOT_TOKEN:}
  XAUTHID: ${IOT_XAUTH_ID:}
  callBackUrl: ${IOT_CALLBACK_URL}

# elk
app:
  id: e-hub-upstream
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        uri: http://10.39.61.11:8086
        enabled: true
        db: applications
    web:
      server:
        request:
          autotime:
            enabled: true

devops:
  logging:
    topic: fnw_logging_kafka_topic_pre

# swagger
swagger:
  enable: true
