org.apache.wss4j.crypto.provider=org.apache.wss4j.common.crypto.Merlin
org.apache.wss4j.crypto.merlin.keystore.type=PKCS12
org.apache.wss4j.crypto.merlin.keystore.private.password=Huabei.zdh2019
org.apache.wss4j.crypto.merlin.keystore.alias=webclient
org.apache.wss4j.crypto.merlin.keystore.password=Huabei.zdh2019
org.apache.wss4j.crypto.merlin.keystore.file=jks/webclient1.p12

org.apache.wss4j.crypto.merlin.truststore.file=jks/webclient.truststore
org.apache.wss4j.crypto.merlin.truststore.password=Huabei.zdh2019