-- 电网上送质量核查完整表结构（一至四期）
CREATE TABLE IF NOT EXISTS la_grid_delivery_period (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  period_code VARCHAR(64) NOT NULL,
  period_name VARCHAR(128) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE' COMMENT 'PLANNED/ACTIVE/ENDED/DISABLED',
  standard_rate DECIMAL(10,4) NOT NULL DEFAULT 99,
  required_days INT NOT NULL DEFAULT 7,
  remark VARCHAR(512) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_period_code (aggregator_id, period_code),
  KEY idx_la_grid_period_date (aggregator_id, resource_type_id, start_date, end_date, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='聚合商电网上送周期';

CREATE TABLE IF NOT EXISTS la_grid_market_status (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  resource_type_id VARCHAR(64) NOT NULL,
  market_enabled TINYINT NOT NULL DEFAULT 1 COMMENT '1参与市场，0当前未参与；仅作人工页面标记',
  remark VARCHAR(512) DEFAULT NULL,
  operator_id VARCHAR(64) DEFAULT NULL,
  operator_name VARCHAR(128) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_market_status (aggregator_id, resource_type_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电网市场参与人工标记';
CREATE TABLE IF NOT EXISTS la_model_snapshot (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  snapshot_code VARCHAR(64) NOT NULL,
  snapshot_name VARCHAR(128) DEFAULT NULL,
  effective_start DATETIME NOT NULL,
  effective_end DATETIME DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'EFFECTIVE',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_snapshot_code (aggregator_id, snapshot_code),
  KEY idx_la_snapshot_effective (aggregator_id, effective_start, effective_end, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='负荷聚合历史参与快照';

CREATE TABLE IF NOT EXISTS la_model_snapshot_device (
  id BIGINT NOT NULL AUTO_INCREMENT,
  snapshot_id BIGINT NOT NULL,
  aggregator_id VARCHAR(20) NOT NULL,
  ent_id VARCHAR(20) DEFAULT NULL,
  device_id BIGINT DEFAULT NULL,
  device_code VARCHAR(128) NOT NULL,
  point_code VARCHAR(64) NOT NULL DEFAULT 'P',
  single_code VARCHAR(128) DEFAULT NULL,
  single_name VARCHAR(128) DEFAULT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL,
  participation_status TINYINT NOT NULL DEFAULT 1 COMMENT '1参与，0不参与',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_snapshot_device (snapshot_id, device_code, point_code),
  KEY idx_la_snapshot_device_scope (aggregator_id, snapshot_id, participation_status, single_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='负荷聚合快照设备';

CREATE TABLE IF NOT EXISTS la_grid_delivery_batch (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  data_date DATE NOT NULL,
  delivery_type VARCHAR(32) NOT NULL COMMENT 'TOTAL/SINGLE_MEAS',
  resource_type_id VARCHAR(64) DEFAULT NULL,
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  snapshot_id BIGINT DEFAULT NULL,
  expected_count INT DEFAULT 0,
  prepared_count INT DEFAULT 0,
  sent_time DATETIME DEFAULT NULL,
  response_time DATETIME DEFAULT NULL,
  send_status VARCHAR(32) NOT NULL DEFAULT 'PREPARED',
  response_code VARCHAR(64) DEFAULT NULL,
  response_message VARCHAR(1024) DEFAULT NULL,
  request_payload LONGTEXT,
  response_payload LONGTEXT,
  attempt_no INT NOT NULL DEFAULT 1,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_la_grid_batch_scope (aggregator_id, resource_type_id, data_date, delivery_type, grid_channel_no),
  KEY idx_la_grid_batch_status (send_status, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电网上送审计批次';

CREATE TABLE IF NOT EXISTS la_grid_total_minute (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  aggregator_id VARCHAR(20) NOT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  minute_time DATETIME NOT NULL,
  total_value DECIMAL(20,6) DEFAULT NULL,
  has_value TINYINT NOT NULL DEFAULT 0,
  quality VARCHAR(32) NOT NULL DEFAULT 'missing',
  source_type VARCHAR(32) DEFAULT NULL,
  send_status VARCHAR(32) DEFAULT NULL,
  receive_time DATETIME DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_total_minute (batch_id, grid_channel_no, minute_time),
  KEY idx_la_grid_total_query (aggregator_id, resource_type_id, minute_time, grid_channel_no),
  KEY idx_la_grid_total_latest (aggregator_id, resource_type_id, grid_channel_no, minute_time, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实际上送总加分钟明细';

CREATE TABLE IF NOT EXISTS la_grid_single_quarter (
  id BIGINT NOT NULL AUTO_INCREMENT,
  batch_id BIGINT NOT NULL,
  snapshot_id BIGINT DEFAULT NULL,
  aggregator_id VARCHAR(20) NOT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  single_code VARCHAR(128) NOT NULL,
  ent_id VARCHAR(20) DEFAULT NULL,
  device_id BIGINT DEFAULT NULL,
  quarter_time DATETIME NOT NULL,
  active_power DECIMAL(20,6) DEFAULT NULL,
  reactive_power DECIMAL(20,6) DEFAULT NULL,
  current_value DECIMAL(20,6) DEFAULT NULL,
  electric_quantity DECIMAL(20,6) DEFAULT NULL,
  has_value TINYINT NOT NULL DEFAULT 0,
  quality VARCHAR(32) NOT NULL DEFAULT 'missing',
  send_status VARCHAR(32) DEFAULT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_single_quarter (batch_id, single_code, quarter_time),
  KEY idx_la_grid_single_query (aggregator_id, resource_type_id, quarter_time, grid_channel_no),
  KEY idx_la_grid_single_code (single_code, quarter_time),
  KEY idx_la_grid_single_latest (aggregator_id, resource_type_id, grid_channel_no, quarter_time, single_code, id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='实际上送单体15分钟明细';

CREATE TABLE IF NOT EXISTS la_grid_reconciliation (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  data_date DATE NOT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  quarter_time DATETIME NOT NULL,
  snapshot_id BIGINT DEFAULT NULL,
  total_value DECIMAL(20,6) DEFAULT NULL,
  single_sum DECIMAL(20,6) DEFAULT NULL,
  difference DECIMAL(20,6) DEFAULT NULL,
  relative_difference DECIMAL(20,8) DEFAULT NULL,
  tolerance DECIMAL(20,6) DEFAULT NULL,
  reconciliation_status VARCHAR(32) NOT NULL DEFAULT 'UNKNOWN',
  missing_single_count INT NOT NULL DEFAULT 0,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_reconcile (aggregator_id, resource_type_id, grid_channel_no, quarter_time),
  KEY idx_la_grid_reconcile_date (aggregator_id, resource_type_id, data_date, reconciliation_status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='总加单体对账结果';

CREATE TABLE IF NOT EXISTS la_grid_quality_issue (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  data_date DATE NOT NULL,
  period_id BIGINT DEFAULT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  issue_key VARCHAR(255) NOT NULL COMMENT '同一问题的幂等业务键',
  issue_type VARCHAR(32) NOT NULL,
  issue_time DATETIME NOT NULL,
  grid_channel_no VARCHAR(64) DEFAULT NULL,
  single_code VARCHAR(128) DEFAULT NULL,
  device_id BIGINT DEFAULT NULL,
  reason VARCHAR(512) DEFAULT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'OPEN',
  remark VARCHAR(1024) DEFAULT NULL,
  handler_id VARCHAR(64) DEFAULT NULL,
  handler_name VARCHAR(128) DEFAULT NULL,
  first_detected_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_detected_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_time DATETIME DEFAULT NULL,
  current_detected TINYINT NOT NULL DEFAULT 1 COMMENT '本次自动核查是否仍存在',
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_issue_key (aggregator_id, issue_key),
  KEY idx_la_grid_issue_query (aggregator_id, data_date, issue_type, status),
  KEY idx_la_grid_issue_period (aggregator_id, period_id, data_date, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电网上送质量问题';

CREATE TABLE IF NOT EXISTS la_grid_quality_daily (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  data_date DATE NOT NULL,
  period_id BIGINT DEFAULT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  snapshot_id BIGINT DEFAULT NULL,
  participant_count INT NOT NULL DEFAULT 0,
  total_expected INT NOT NULL DEFAULT 0,
  total_actual INT NOT NULL DEFAULT 0,
  total_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  single_expected INT NOT NULL DEFAULT 0,
  single_actual INT NOT NULL DEFAULT 0,
  single_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  reconciliation_expected INT NOT NULL DEFAULT 0,
  reconciliation_matched INT NOT NULL DEFAULT 0,
  reconciliation_rate DECIMAL(10,4) NOT NULL DEFAULT 0,
  issue_count INT NOT NULL DEFAULT 0,
  reached_standard TINYINT NOT NULL DEFAULT 0,
  calculated_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_quality_daily (aggregator_id, resource_type_id, grid_channel_no, data_date),
  KEY idx_la_grid_quality_daily_date (aggregator_id, resource_type_id, data_date),
  KEY idx_la_grid_quality_daily_period (aggregator_id, period_id, resource_type_id, data_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电网上送每日质量汇总';

CREATE TABLE IF NOT EXISTS la_grid_export_task (
  id BIGINT NOT NULL AUTO_INCREMENT,
  task_no VARCHAR(64) NOT NULL,
  aggregator_id VARCHAR(20) NOT NULL,
  period_id BIGINT DEFAULT NULL,
  resource_type_id VARCHAR(64) DEFAULT NULL COMMENT '能源类型ID',
  report_type VARCHAR(32) NOT NULL DEFAULT 'FULL',
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  grid_channel_no VARCHAR(64) NOT NULL DEFAULT '',
  task_status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  progress INT NOT NULL DEFAULT 0,
  file_name VARCHAR(255) DEFAULT NULL,
  file_path VARCHAR(1024) DEFAULT NULL,
  error_message VARCHAR(1024) DEFAULT NULL,
  created_by VARCHAR(64) DEFAULT NULL,
  finish_time DATETIME DEFAULT NULL,
  expire_time DATETIME DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  update_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uk_la_grid_export_task_no (task_no),
  KEY idx_la_grid_export_task_query (aggregator_id, create_time, task_status),
  KEY idx_la_grid_export_task_period (aggregator_id, period_id, resource_type_id, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电网上送异步导出任务';

CREATE TABLE IF NOT EXISTS la_grid_manual_operation (
  id BIGINT NOT NULL AUTO_INCREMENT,
  aggregator_id VARCHAR(20) NOT NULL,
  resource_type_id VARCHAR(64) NOT NULL,
  operation_type VARCHAR(32) NOT NULL COMMENT 'SEND_MODEL/RETRY_SINGLE/SEND_PEAK_96/SEND_PEAK_DAILY',
  business_time DATETIME DEFAULT NULL,
  operation_status VARCHAR(32) NOT NULL COMMENT 'SUCCESS/FAILED',
  response_message VARCHAR(2048) DEFAULT NULL,
  operator_id VARCHAR(64) DEFAULT NULL,
  operator_name VARCHAR(128) DEFAULT NULL,
  create_time DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_la_grid_manual_operation (aggregator_id, resource_type_id, operation_type, create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电网上送人工操作记录';
