spring:
  profiles:
    active: dev
  application:
    name: e-hub-console
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
  messages:
    basename: i18n/Messages,i18n/Pages
  main:
    allow-bean-definition-overriding: true

# 聚合商自动申报计划配置
aggregator:
  apply:
    plan:
      aggregatorId: 1711340903453614082

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    cn.sl.ehub: debug

mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

server:
  port: 8009
