spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.39.48.241:3306/load-aggregator?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    #    username: fn_db_test
    #    password: fn_db_test20180411
    username: rootroot
    password: Abcd1234

  # redis
  redis:
    sentinel:
      master: master6379
      nodes: 10.39.47.6:26379,10.39.47.7:26379,10.39.47.8:26379
    #    host: 10.39.47.244
    #    port: 6379
    database: 15
    password: FNpreadmin123
    timeout: 6000
    jedis:
      pool:
        max-active: 300
        min-idle: 10
        max-idle: 100
        max-wait: 4000
        test-on-create: false
        test-on-borrow: true
        test-on-return: false
        test-while-idle: true

#大数据
bigdata:
  simulate: http://bigdata-api-simulate.pre.fnwintranet.com
  userKey: e1771cda571d696e843c5c055bdd8e32_e-hub-console
  data-collector: http://data-collector.fnwintranet.com

#监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      influx:
        uri: http://10.39.61.11:8086
        enabled: true
        db: applications
    web:
      server:
        request:
          autotime:
            enabled: true

#appId
app:
  id: e-hub-console

#ELK
devops:
  logging:
    topic: fnw_logging_kafka_topic_pre

logging:
  kafka:
    topic: fnw_logging_kafka_topic_prod
    app-id: e-hub-console-prod
    level: INFO

influxUrl: http://10.39.46.5:8086
database: logstash
measurement: e-hub-console-measurement-prod

swagger:
  enable: true

# FDFS
fdfs:
  connect-timeout: 601
  so-timeout: 1501
  tracker-list: #TrackerList参数,支持多个
    - 10.39.48.66:22122
    - 10.39.48.67:22122
  thumb-image: #缩略图生成参数
    width: 150
    height: 150
  web-server-url: https://img.fanneng.com

sms:
  applicationName: load-aggregator
  appId: msg-5229460204476416
  appSecret: pwd-15600168730
  templateCode: SMS_206890159
  userTemplateCode: SMS_210068206
  url: http://cloud-sms.cloud-common.fnwrancher-dev.enncloud.cn


upload:
  url: http://10.39.48.69:18080/group1/upload
  path: data/e-hub-console/work
download:
  url: https://files.fanneng.com

cim:
  appToken: e1771cda571d696e843c5c055bdd8e32_e-hub-console