package cn.sl.ehub.service.vo;

import java.io.Serializable;
import java.util.Date;

public class AggregatorDapChart implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregator_dap_chart.id
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregator_dap_chart.aggregator_id
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    private String aggregatorId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregator_dap_chart.resource_type
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    private String resourceType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregator_dap_chart.date
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column aggregator_dap_chart.dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    private String dapChart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aggregator_dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregator_dap_chart.id
     *
     * @return the value of aggregator_dap_chart.id
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregator_dap_chart.id
     *
     * @param id the value for aggregator_dap_chart.id
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregator_dap_chart.aggregator_id
     *
     * @return the value of aggregator_dap_chart.aggregator_id
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public String getAggregatorId() {
        return aggregatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregator_dap_chart.aggregator_id
     *
     * @param aggregatorId the value for aggregator_dap_chart.aggregator_id
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public void setAggregatorId(String aggregatorId) {
        this.aggregatorId = aggregatorId == null ? null : aggregatorId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregator_dap_chart.resource_type
     *
     * @return the value of aggregator_dap_chart.resource_type
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public String getResourceType() {
        return resourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregator_dap_chart.resource_type
     *
     * @param resourceType the value for aggregator_dap_chart.resource_type
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public void setResourceType(String resourceType) {
        this.resourceType = resourceType == null ? null : resourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregator_dap_chart.date
     *
     * @return the value of aggregator_dap_chart.date
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregator_dap_chart.date
     *
     * @param date the value for aggregator_dap_chart.date
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aggregator_dap_chart.dap_chart
     *
     * @return the value of aggregator_dap_chart.dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public String getDapChart() {
        return dapChart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aggregator_dap_chart.dap_chart
     *
     * @param dapChart the value for aggregator_dap_chart.dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    public void setDapChart(String dapChart) {
        this.dapChart = dapChart == null ? null : dapChart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggregator_dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", aggregatorId=").append(aggregatorId);
        sb.append(", resourceType=").append(resourceType);
        sb.append(", date=").append(date);
        sb.append(", dapChart=").append(dapChart);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggregator_dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        AggregatorDapChart other = (AggregatorDapChart) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getAggregatorId() == null ? other.getAggregatorId() == null : this.getAggregatorId().equals(other.getAggregatorId()))
            && (this.getResourceType() == null ? other.getResourceType() == null : this.getResourceType().equals(other.getResourceType()))
            && (this.getDate() == null ? other.getDate() == null : this.getDate().equals(other.getDate()))
            && (this.getDapChart() == null ? other.getDapChart() == null : this.getDapChart().equals(other.getDapChart()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aggregator_dap_chart
     *
     * @mbg.generated Fri Apr 26 02:25:57 UTC 2024
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getAggregatorId() == null) ? 0 : getAggregatorId().hashCode());
        result = prime * result + ((getResourceType() == null) ? 0 : getResourceType().hashCode());
        result = prime * result + ((getDate() == null) ? 0 : getDate().hashCode());
        result = prime * result + ((getDapChart() == null) ? 0 : getDapChart().hashCode());
        return result;
    }
}