<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions name="GreeterImplService" targetNamespace="http://webservice.nari.com/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://webservice.nari.com/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns1="http://schemas.xmlsoap.org/soap/http">
   <wsdl:types>
      <xs:schema attributeFormDefault="unqualified" elementFormDefault="unqualified" targetNamespace="http://webservice.nari.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
         <xs:element name="cmd" type="tns:cmd"/>
         <xs:element name="cmdResponse" type="tns:cmdResponse"/>
         <xs:element name="commitFile" type="tns:commitFile"/>
         <xs:element name="commitFileResponse" type="tns:commitFileResponse"/>
         <xs:element name="declare" type="tns:declare"/>
         <xs:element name="declareResponse" type="tns:declareResponse"/>
         <xs:complexType name="declare">
            <xs:sequence>
               <xs:element minOccurs="0" name="cmdData" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
         <xs:complexType name="declareResponse">
            <xs:sequence>
               <xs:element minOccurs="0" name="return" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
         <xs:complexType name="cmd">
            <xs:sequence>
               <xs:element minOccurs="0" name="cmdData" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
         <xs:complexType name="cmdResponse">
            <xs:sequence>
               <xs:element minOccurs="0" name="return" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
         <xs:complexType name="commitFile">
            <xs:sequence>
               <xs:element minOccurs="0" name="filename" type="xs:string"/>
               <xs:element minOccurs="0" name="filebyte" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
         <xs:complexType name="commitFileResponse">
            <xs:sequence>
               <xs:element minOccurs="0" name="return" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
         <xs:element name="Exception" type="tns:Exception"/>
         <xs:complexType name="Exception">
            <xs:sequence>
               <xs:element minOccurs="0" name="message" type="xs:string"/>
            </xs:sequence>
         </xs:complexType>
      </xs:schema>
   </wsdl:types>
   <wsdl:message name="declare">
      <wsdl:part element="tns:declare" name="parameters"/>
   </wsdl:message>
   <wsdl:message name="Exception">
      <wsdl:part element="tns:Exception" name="Exception"/>
   </wsdl:message>
   <wsdl:message name="declareResponse">
      <wsdl:part element="tns:declareResponse" name="parameters"/>
   </wsdl:message>
   <wsdl:message name="cmd">
      <wsdl:part element="tns:cmd" name="parameters"/>
   </wsdl:message>
   <wsdl:message name="cmdResponse">
      <wsdl:part element="tns:cmdResponse" name="parameters"/>
   </wsdl:message>
   <wsdl:message name="commitFile">
      <wsdl:part element="tns:commitFile" name="parameters"/>
   </wsdl:message>
   <wsdl:message name="commitFileResponse">
      <wsdl:part element="tns:commitFileResponse" name="parameters"/>
   </wsdl:message>
   <wsdl:portType name="Greeter">
      <wsdl:operation name="declare">
         <wsdl:input message="tns:declare" name="declare"/>
         <wsdl:output message="tns:declareResponse" name="declareResponse"/>
      </wsdl:operation>
      <wsdl:operation name="cmd">
         <wsdl:input message="tns:cmd" name="cmd"/>
         <wsdl:output message="tns:cmdResponse" name="cmdResponse"/>
      </wsdl:operation>
      <wsdl:operation name="commitFile">
         <wsdl:input message="tns:commitFile" name="commitFile"/>
         <wsdl:output message="tns:commitFileResponse" name="commitFileResponse"/>
         <wsdl:fault message="tns:Exception" name="Exception"/>
      </wsdl:operation>
   </wsdl:portType>
   <wsdl:binding name="GreeterImplServiceSoapBinding" type="tns:Greeter">
      <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
      <wsdl:operation name="declare">
         <soap:operation soapAction="" style="document"/>
         <wsdl:input name="declare">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="declareResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="cmd">
         <soap:operation soapAction="" style="document"/>
         <wsdl:input name="cmd">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="cmdResponse">
            <soap:body use="literal"/>
         </wsdl:output>
      </wsdl:operation>
      <wsdl:operation name="commitFile">
         <soap:operation soapAction="" style="document"/>
         <wsdl:input name="commitFile">
            <soap:body use="literal"/>
         </wsdl:input>
         <wsdl:output name="commitFileResponse">
            <soap:body use="literal"/>
         </wsdl:output>
         <wsdl:fault name="Exception">
            <soap:fault name="Exception" use="literal"/>
         </wsdl:fault>
      </wsdl:operation>
   </wsdl:binding>
   <wsdl:service name="GreeterImplService">
      <wsdl:port binding="tns:GreeterImplServiceSoapBinding" name="GreeterImplPort">
         <soap:address location="https://192.168.32.11:39091/PostValue"/>
      </wsdl:port>
   </wsdl:service>
</wsdl:definitions>