package cn.sl.ehub.upstream.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-08T14:54:32.484+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://webservice.nari.com/", name = "GetFile")
@XmlSeeAlso({ObjectFactory.class})
public interface GetFile {

    @WebMethod
    @RequestWrapper(localName = "getDeclare", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.GetDeclare")
    @ResponseWrapper(localName = "getDeclareResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.GetDeclareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getDeclare(

        @WebParam(name = "type", targetNamespace = "")
        String type
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "test", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.Test")
    @ResponseWrapper(localName = "testResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.TestResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String test(

        @WebParam(name = "test", targetNamespace = "")
        String test
    );

    @WebMethod
    @RequestWrapper(localName = "getRecallDeclare", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.GetRecallDeclare")
    @ResponseWrapper(localName = "getRecallDeclareResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.GetRecallDeclareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String getRecallDeclare(

        @WebParam(name = "type", targetNamespace = "")
        String type,
        @WebParam(name = "recalldate", targetNamespace = "")
        String recalldate
    ) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "commitFile", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.CommitFile")
    @ResponseWrapper(localName = "commitFileResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.CommitFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String commitFile(

        @WebParam(name = "filename", targetNamespace = "")
        String filename,
        @WebParam(name = "filebyte", targetNamespace = "")
        String filebyte
    ) throws Exception_Exception;
}
