package cn.sl.ehub.upstream.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-08T14:54:32.505+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "GetFileImplService",
                  wsdlLocation = "classpath:wsdl/GetFileService.wsdl",
                  targetNamespace = "http://webservice.nari.com/")
public class GetFileImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.nari.com/", "GetFileImplService");
    public final static QName GetFileImplPort = new QName("http://webservice.nari.com/", "GetFileImplPort");
    static {
        URL url = null;
        try {
            url = new URL("classpath:wsdl/GetFileService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetFileImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GetFileService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetFileImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetFileImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetFileImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GetFileImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GetFileImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GetFileImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns GetFile
     */
    @WebEndpoint(name = "GetFileImplPort")
    public GetFile getGetFileImplPort() {
        return super.getPort(GetFileImplPort, GetFile.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetFile
     */
    @WebEndpoint(name = "GetFileImplPort")
    public GetFile getGetFileImplPort(WebServiceFeature... features) {
        return super.getPort(GetFileImplPort, GetFile.class, features);
    }

}
