package cn.sl.ehub.upstream.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-08T14:54:32.685+08:00
 * Generated source version: 3.4.0
 *
 */
@WebService(targetNamespace = "http://webservice.nari.com/", name = "Greeter")
@XmlSeeAlso({ ObjectFactory.class })
public interface Greeter {

    @WebMethod
    @RequestWrapper(localName = "declare", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.Declare")
    @ResponseWrapper(localName = "declareResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.DeclareResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String declare(

            @WebParam(name = "cmdData", targetNamespace = "") String cmdData);

    @WebMethod
    @RequestWrapper(localName = "cmd", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.Cmd")
    @ResponseWrapper(localName = "cmdResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.CmdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String cmd(

            @WebParam(name = "cmdData", targetNamespace = "") String cmdData);

    @WebMethod
    @RequestWrapper(localName = "commitFile", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.CommitFile")
    @ResponseWrapper(localName = "commitFileResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.CommitFileResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String commitFile(

            @WebParam(name = "filename", targetNamespace = "") String filename,
            @WebParam(name = "filebyte", targetNamespace = "") String filebyte) throws Exception_Exception;

    @WebMethod
    @RequestWrapper(localName = "declareBid", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.DeclareBid")
    @ResponseWrapper(localName = "declareBidResponse", targetNamespace = "http://webservice.nari.com/", className = "cn.sl.ehub.upstream.ws.DeclareBidResponse")
    @WebResult(name = "return", targetNamespace = "")
    public String declareBid(

            @WebParam(name = "cmdData", targetNamespace = "") String cmdData);
}
