package cn.sl.ehub.upstream.ws;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.4.0
 * 2020-11-08T14:54:32.693+08:00
 * Generated source version: 3.4.0
 *
 */
@WebServiceClient(name = "GreeterImplService",
                  wsdlLocation = "classpath:wsdl/GreeterService.wsdl",
                  targetNamespace = "http://webservice.nari.com/")
public class GreeterImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.nari.com/", "GreeterImplService");
    public final static QName GreeterImplPort = new QName("http://webservice.nari.com/", "GreeterImplPort");
    static {
        URL url = null;
        try {
            url = new URL("classpath:wsdl/GreeterService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GreeterImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/GreeterService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GreeterImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GreeterImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GreeterImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public GreeterImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public GreeterImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public GreeterImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "GreeterImplPort")
    public Greeter getGreeterImplPort() {
        return super.getPort(GreeterImplPort, Greeter.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Greeter
     */
    @WebEndpoint(name = "GreeterImplPort")
    public Greeter getGreeterImplPort(WebServiceFeature... features) {
        return super.getPort(GreeterImplPort, Greeter.class, features);
    }

}
